DUT\Models\Article:
  type: entity
  
  oneToMany:
    commentaires:
      targetEntity: Commentaire
      mappedBy: article

  table: Article
  
  id:
    id:
      type: integer
      generator:
        strategy: auto

  fields:
    auteur:
      type: integer
      column: id_redacteur
      nullable: false
    
    titre:
      type: string
      column: titre
      nullable: false
        
    contenu:
      type: string
      column: contenu
      nullable: false
